# Generated by Django 3.1.4 on 2020-12-31 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0005_auto_20201229_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezept',
            name='aktuellerProzess',
            field=models.CharField(choices=[('heizen', 'Aufheizen'), ('einmaischen', 'Einmaischen'), ('ersteRast', '1. Rast'), ('zweiteRast', '2. Rast'), ('dritteRast', '3. Rast'), ('vierteRast', '4. Rast'), ('abmaischen', 'Abmaischen'), ('läutern', 'Läutern'), ('kochen', 'Kochen'), ('kühlen', 'Kühlen'), ('gärung', 'Gärung'), ('ende', 'Ende')], default='heizen', max_length=120),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='datum',
            field=models.DateField(default=datetime.date(2020, 12, 31)),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='naechsterProzess',
            field=models.CharField(choices=[('heizen', 'Aufheizen'), ('einmaischen', 'Einmaischen'), ('ersteRast', '1. Rast'), ('zweiteRast', '2. Rast'), ('dritteRast', '3. Rast'), ('vierteRast', '4. Rast'), ('abmaischen', 'Abmaischen'), ('läutern', 'Läutern'), ('kochen', 'Kochen'), ('kühlen', 'Kühlen'), ('gärung', 'Gärung'), ('ende', 'Ende')], default='einmaischen', max_length=120),
        ),
        migrations.AlterField(
            model_name='temperaturlogging',
            name='zeitstempel',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
