# Generated by Django 3.1.4 on 2020-12-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0007_auto_20201231_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturlogging',
            name='sollwert',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
