# Generated by Django 3.1.5 on 2021-01-19 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0008_temperaturlogging_sollwert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezept',
            name='datum',
            field=models.DateField(default=datetime.date(2021, 1, 19)),
        ),
    ]
