# Generated by Django 3.1.4 on 2020-12-27 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rezept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=datetime.date(2020, 12, 27))),
                ('titel', models.CharField(max_length=120)),
                ('stil', models.CharField(max_length=120)),
                ('zielvolumen', models.DecimalField(decimal_places=1, max_digits=3)),
                ('hauptguss', models.DecimalField(decimal_places=1, max_digits=3)),
                ('nachguss', models.DecimalField(decimal_places=1, max_digits=3)),
                ('stammwuerze', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('restextrakt', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('alkohol', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('hefe', models.CharField(max_length=120)),
                ('bittere', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('hopfenkochzeit', models.DecimalField(decimal_places=0, max_digits=3)),
                ('karbonisierung', models.DecimalField(blank=True, decimal_places=1, default=5.0, max_digits=3)),
                ('notizen', models.TextField(blank=True)),
                ('logging', models.BooleanField(default=False)),
                ('intervall', models.DecimalField(decimal_places=0, default=180, max_digits=3)),
                ('prozessschritt', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
            ],
            options={
                'verbose_name_plural': 'Rezepte',
            },
        ),
        migrations.CreateModel(
            name='Temperaturlogging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField(auto_now=True)),
                ('sensor1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sensor2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prozess', models.CharField(max_length=120)),
                ('rezept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezepte.rezept')),
            ],
            options={
                'verbose_name_plural': 'Temperaturlogging',
            },
        ),
        migrations.CreateModel(
            name='Malz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorte', models.CharField(max_length=120)),
                ('menge', models.DecimalField(decimal_places=2, max_digits=4)),
                ('notizen', models.TextField(blank=True)),
                ('rezept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezepte.rezept')),
            ],
            options={
                'verbose_name_plural': 'Malz',
            },
        ),
        migrations.CreateModel(
            name='Maischen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prozess', models.CharField(choices=[('einmaischen', 'Einmaischen'), ('1. Rast', '1. Rast'), ('2. Rast', '2. Rast'), ('3. Rast', '3. Rast'), ('4. Rast', '4. Rast'), ('abmaischen', 'Abmaischen')], max_length=120)),
                ('temperatur', models.DecimalField(decimal_places=1, max_digits=3)),
                ('dauer', models.DecimalField(decimal_places=2, max_digits=4)),
                ('notizen', models.TextField(blank=True)),
                ('rezept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezepte.rezept')),
            ],
            options={
                'verbose_name_plural': 'Maischen',
            },
        ),
        migrations.CreateModel(
            name='Hopfenplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hopfen', models.CharField(max_length=120)),
                ('menge', models.DecimalField(decimal_places=1, max_digits=3)),
                ('verwendung', models.CharField(choices=[('kochen', 'Kochen'), ('whirlpool', 'Whirlpool'), ('stopfen', 'Stopfen')], max_length=120)),
                ('dauer', models.DecimalField(decimal_places=2, max_digits=4)),
                ('temperatur', models.DecimalField(decimal_places=1, max_digits=3)),
                ('notizen', models.TextField(blank=True)),
                ('rezept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezepte.rezept')),
            ],
            options={
                'verbose_name_plural': 'Hopfenplan',
            },
        ),
    ]
