# Generated by Django 3.1.4 on 2020-12-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezept',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
