# Generated by Django 3.1.4 on 2020-12-28 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0002_rezept_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezept',
            name='prozessschritt',
        ),
        migrations.AddField(
            model_name='rezept',
            name='aktuellerProzess',
            field=models.CharField(choices=[('heizen', 'Aufheizen'), ('einmaischen', 'Einmaischen'), ('ersteRast', '1. Rast'), ('zweiteRast', '2. Rast'), ('dritteRast', '3. Rast'), ('vierteRast', '4. Rast'), ('abmaischen', 'Abmaischen'), ('läutern', 'Läutern'), ('kochen', 'Kochen'), ('gärung', 'Gärung')], default='heizen', max_length=120),
        ),
        migrations.AddField(
            model_name='rezept',
            name='naechsterProzess',
            field=models.CharField(choices=[('heizen', 'Aufheizen'), ('einmaischen', 'Einmaischen'), ('ersteRast', '1. Rast'), ('zweiteRast', '2. Rast'), ('dritteRast', '3. Rast'), ('vierteRast', '4. Rast'), ('abmaischen', 'Abmaischen'), ('läutern', 'Läutern'), ('kochen', 'Kochen'), ('gärung', 'Gärung')], default='einmaischen', max_length=120),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='datum',
            field=models.DateField(default=datetime.date(2020, 12, 28)),
        ),
    ]
