# Generated by Django 3.1.4 on 2020-12-28 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0003_auto_20201228_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezept',
            name='zeitstempelProzess',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 1, 1, 0)),
        ),
    ]
