# Generated by Django 3.1.4 on 2020-12-29 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0004_rezept_zeitstempelprozess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maischen',
            name='prozess',
            field=models.CharField(choices=[('einmaischen', 'Einmaischen'), ('ersteRast', '1. Rast'), ('zweiteRast', '2. Rast'), ('dritteRast', '3. Rast'), ('vierteRast', '4. Rast'), ('abmaischen', 'Abmaischen')], max_length=120),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='datum',
            field=models.DateField(default=datetime.date(2020, 12, 29)),
        ),
    ]
