# Generated by Django 3.1.4 on 2020-12-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0006_auto_20201231_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturlogging',
            name='zeitstempel',
            field=models.DateTimeField(),
        ),
    ]
